INSERT INTO blogful_articles (title, date_published, content)
VALUES
    ('101 Dalmations', now() - '19 days'::INTERVAL, 'A lady tries to make a coat.'),
    ('Balto', now() - '18 days'::INTERVAL, 'A dog carries medicine in Alaska.'),
    ('All Dogs go to Heaven', now() - '17 days'::INTERVAL, 'A dog dies, but comes back as a ghost.'),
    ('Snow Dogs', now() - '16 days'::INTERVAL, 'A Cuba Gooding Jr. vehicle.'),
    ('Hotel for Dogs', now() - '15 days'::INTERVAL, 'A hotel, but for dogs.'),
    ('Marley and me', now() - '14 days'::INTERVAL, null),
    ('A Dog''s purpose', now() - '13 days'::INTERVAL, 'An exploration of reincarnation.'),
    ('Lady and the Tramp', now() - '12 days'::INTERVAL, 'Two dogs share a spaghetti kiss.'),
    ('The Secret Life of Pets', now() - '11 days'::INTERVAL, null),
    ('Isle of Dogs', now() - '10 days'::INTERVAL, 'It sounds like I love Dogs.'),
    ('Beethoven', now() - '9 days'::INTERVAL, 'A family gets a comically large dog.'),
    ('Clifford the Big Red Dog', now() - '8 days'::INTERVAL, 'A little girl gets a dog that is so large it isn''t funny.'),
    ('Air Bud', now() - '7 days'::INTERVAL, 'Dogs CAN play basketball.'),
    ('Bolt', now() - '6 days'::INTERVAL, 'Action star animal believes his own hype.'),
    ('Because of Winn-Dixie', now() - '5 days'::INTERVAL, null),
    ('Lassie', now() - '4 days'::INTERVAL, 'A child falls down a well.'),
    ('Show Dogs', now() - '3 days'::INTERVAL, null),
    ('The Adventures of Milo and Otis', now() - '2 days'::INTERVAL, 'A film worth fighting for.'),
    ('Cujo', now() - '1 days'::INTERVAL, 'Less feel-good than the others.'),
    ('Step Dogs', now(), 'A country dog and city dog forge an unlikely alliance.'),
    ('Benji', now(), 'A stray dog just tries to live his life.'),
    ('102 Dalmations', now(), 'This time with one more dalmation.')